# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='parner/contracts'),
        ),
    ]
