# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_partner_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Precio')),
                ('quantity', models.SmallIntegerField(default=1)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('image', models.ImageField(upload_to='product')),
                ('created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='store.Category')),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('porcent', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Descuento')),
                ('created', models.DateTimeField(auto_now=True)),
                ('start', models.DateField(auto_now=True)),
                ('end', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('class_css', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('-created',), 'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ('-created',), 'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouses'},
        ),
        migrations.AlterField(
            model_name='partner',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='partner/contracts'),
        ),
        migrations.AddField(
            model_name='product',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_partner', to='store.Partner'),
        ),
        migrations.AddField(
            model_name='product',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_promotion', to='store.Promotion'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_status', to='store.Status'),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_warehouse', to='store.Warehouse'),
        ),
    ]
