# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20181125_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shortname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_promotion', to='store.Promotion'),
        ),
    ]
