# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20181126_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Costo')),
                ('quantity', models.SmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'ProductWarehouse',
                'verbose_name_plural': 'ProductWarehouse',
            },
        ),
        migrations.CreateModel(
            name='QuantityDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mult', models.SmallIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name': 'QuantityDiscount',
                'verbose_name_plural': 'QuantityDiscount',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sendcost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='productwarehouse',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_productwarehouse', to='store.Product'),
        ),
        migrations.AddField(
            model_name='productwarehouse',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_productwarehouse', to='store.Status'),
        ),
        migrations.AddField(
            model_name='productwarehouse',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_productwarehouse', to='store.Warehouse'),
        ),
    ]
