# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20181126_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Costo'),
        ),
    ]
