# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantitydiscount',
            name='mult',
            field=models.SmallIntegerField(default=0),
        ),
    ]
