# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20181126_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantitydiscount',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
    ]
