# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_image',
            field=models.ImageField(blank=True, null=True, upload_to='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.ImageField(blank=True, null=True, upload_to='specifications'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
    ]
