# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20181125_2025'),
        ('store', '0017_product_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaTemporal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.SmallIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporal_productwarehouse', to='store.ProductWarehouse')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venta_temporal_userprofile', to='userprofile.Profile')),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name': 'Ventas Temporales',
                'verbose_name_plural': 'Ventas Temporales',
            },
        ),
    ]
