# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 05:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_ventatemporal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventatemporal',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venta_temporal_userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
