# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 02:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0019_auto_20181127_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioFacturacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_destinatario', models.CharField(max_length=50)),
                ('apellido_destinatario', models.CharField(max_length=50)),
                ('empresa_destino', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.PositiveSmallIntegerField(choices=[(0, 'Mujer'), (1, 'Hombre')], default=0)),
                ('telefono_destinatario', models.CharField(max_length=10)),
                ('calle', models.CharField(max_length=50)),
                ('numero_calle', models.CharField(max_length=15)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('colonia', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=8)),
                ('ciudad', models.CharField(max_length=50)),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Aguascalientes'), (2, 'Baja California'), (3, 'Baja California Sur'), (4, 'Campeche'), (5, 'Chiapas'), (6, 'Chihuahua'), (7, 'Ciudad de Mexico'), (8, 'Coahuila'), (9, 'Colima'), (10, 'Durango'), (11, 'Estado de Mexico'), (12, 'Guanajuato'), (13, 'Guerrero'), (14, 'Hidalgo'), (15, 'Jalisco'), (16, 'Michoacan'), (17, 'Morelos'), (18, 'Nayarit'), (19, 'Nuevo Leon'), (20, 'Oaxaca'), (21, 'Puebla'), (22, 'Queretaro'), (23, 'Quintana_Roo'), (24, 'San Luis Potosi'), (25, 'Sinaloa'), (26, 'Sonora'), (27, 'Tabasco'), (28, 'Tamaulipas'), (29, 'Tlaxcala'), (30, 'Veracruz'), (31, 'Yucatan'), (32, 'Zacatecas')], default=23)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=100, null=True)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('email_facturacion', models.CharField(blank=True, max_length=50, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enviofacturacion_userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
