# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cantidad_producto',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='venta',
            name='productos',
            field=models.ManyToManyField(to='store.VentaTemporal'),
        ),
    ]
