# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20181128_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventatemporal',
            name='terminada',
            field=models.BooleanField(default=False),
        ),
    ]
