# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 23:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('enterprise_size', models.PositiveSmallIntegerField(choices=[(0, 'Usuario Personal'), (1, 'Emprendedor'), (2, 'Microempresa'), (3, 'Peque\xf1a'), (4, 'Mediana'), (5, 'Grande')], default=0)),
                ('enterprise_type', models.PositiveSmallIntegerField(choices=[(0, 'Industria'), (1, 'Comercio'), (2, 'Servicios'), (3, 'Educacion'), (4, 'Gobierno')], default=1)),
                ('news', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
