# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20181125_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sure',
            field=models.BooleanField(default=True),
        ),
    ]
